---
title: "Assignment 1: Introduction"
author: "Sarah Hall"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: 
Most of my experience with data analytics has been with GIS and Excel. I have experience collecting and analyzing field data in excel, and visualizing large energy resource datasets in GIS. I used R for one undergradaute course, but it was at a very basic level and a few years ago. I have no experience with GIT. 

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident working with different datasets. I also feel confident in my ability to learn and pick-up coding basics.      
 

3. Are there any components of the course about which you feel apprehensive?

> Answer: 
I do feel apprehensive about learning the terminology and workflow of R/Git, but I know once I get to work through more assignments I will start to feel more comfortable. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: 
https://github.com/sarahj-hall/EDE_Fall2025

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
